/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_uugan_ebarimt_BridgePosAPI */

#ifndef _Included_com_github_uugan_ebarimt_BridgePosAPI
#define _Included_com_github_uugan_ebarimt_BridgePosAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_uugan_ebarimt_BridgePosAPI
 * Method:    put
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_uugan_ebarimt_BridgePosAPI_put
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_uugan_ebarimt_BridgePosAPI
 * Method:    returnBill
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_uugan_ebarimt_BridgePosAPI_returnBill
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_uugan_ebarimt_BridgePosAPI
 * Method:    sendData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_uugan_ebarimt_BridgePosAPI_sendData
  (JNIEnv *, jclass);

/*
 * Class:     com_github_uugan_ebarimt_BridgePosAPI
 * Method:    checkApi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_uugan_ebarimt_BridgePosAPI_checkApi
  (JNIEnv *, jclass);

/*
 * Class:     com_github_uugan_ebarimt_BridgePosAPI
 * Method:    getInformation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_uugan_ebarimt_BridgePosAPI_getInformation
  (JNIEnv *, jclass);

/*
 * Class:     com_github_uugan_ebarimt_BridgePosAPI
 * Method:    callFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_uugan_ebarimt_BridgePosAPI_callFunction
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
